server:
  port: 0

spring:
  application:
    name: GATEWAY-APP
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform:
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gateway
      username: root
      password: pass
      authentication-database: admin
  flyway:
    enabled: true
    url: mongodb://localhost:27017/gateway
    user: root
    password: pass
