version: '3.9'

services:

  adminer:
    image: adminer
    container_name: AdminerContainer
    restart: always
    ports:
      - "8888:8080"

  postgres:
    image: postgres:15.4
    container_name: PostgresContainer
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_DB=gateway'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=pass'
      - 'PGPASSWORD=pass'
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #  postgresql:
  #    image: bitnami/postgresql:alpine
  #    ports:
  #      - '5432:5432'
  #    environment:
  #      - POSTGRESQL_DATABASE=postgres
  #      - POSTGRESQL_USERNAME=postgres
  #      - POSTGRESQL_PASSWORD=postgres
  #      - POSTGRESQL_REPLICATION_MODE=master
  #    networks:
  #      - postgres-network
  #    volumes:
  #      - postgresql_master_data:/bitnami/postgresql
  #
  #  dbeaver:
  #    image: dbeaver/cloudbeaver
  #    container_name: DbeaverContainer
  #    ports:
  #      - "8978:8978"
  #    volumes:
  #    - dbeaver-data:/opt/cloudbeaver/workspace

  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: PgAdminContainer
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
    driver: local
    external: false
  pgadmin-data:
    driver: local
    external: false
  dbeaver-data:
    driver: local
    external: false

networks:
  postgres-network:
    name: postgresdb
    driver: bridge
