spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/gateway
    username: root
    password: pass
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/gateway
    user: root
    password: pass
